version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    networks:
      - backend
    volumes:
      - .:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"

networks:
  backend:
    driver: bridge
