version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    networks:
      - backend
    volumes:
      - .:/usr/src/app
    command: npm run dev
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: postgres:12
    hostname: database
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}

networks:
  backend:
    driver: bridge

volumes:
  data: